version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.production
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8080

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .env.production
    profiles:
      - production